# Alacritty Configuration for Windows

# 設定ファイルの自動リロードを有効にする
# live_config_reload = true

# シェル設定
# PowerShellをデフォルトシェルとして使用する場合
# [shell]
# program = "powershell.exe"
# arguments = ["-NoProfile"] # プロファイルをロードしない場合

# cmd.exeをデフォルトシェルとして使用する場合（上記とどちらか一方を有効にする）
[terminal]
shell = {program = "ssh", args = ["arch"] } 

# ウィンドウ設定
[window]
# ウィンドウの初期サイズ（列数と行数）
# dimensions = { columns = 100, lines = 30 }
startup_mode = "Maximized"
decorations = "none"


opacity = 0.8


# ウィンドウのパディング（内部余白）
padding = { x = 10, y = 10 }

# ウィンドウの不透明度 (0.0 - 1.0, 1.0が不透明)
# opacity = 0.9

# ウィンドウのタイトル
title = "Alacritty Terminal"

# スクロールバック履歴の行数
[scrolling]
history = 10000

# フォント設定
[font.normal]
# 通常フォント
family = "Hack Nerd Font Mono"
style = "Regular"
# Cascadia Code PLがインストールされていない場合は、"Consolas"などを使用してください。
# normal = { family = "Consolas", style = "Regular" }

# 太字フォント
# bold = { family = "Cascadia Code PL", style = "Bold" }
# bold = { family = "Consolas", style = "Bold" }

# 斜体フォント
# italic = { family = "Cascadia Code PL", style = "Italic" }
# italic = { family = "Consolas", style = "Italic" }

# 太字斜体フォント
# bold_italic = { family = "Cascadia Code PL", style = "Bold Italic" }
# bold_italic = { family = "Consolas", style = "Bold Italic" }

# フォントサイズ
[font]
size = 15.0

# カラー設定 (Alacrittyのデフォルトダークテーマ)
[colors.primary]
foreground = "#d8d8d8"
background = "#181818"

[colors.normal]
black   = "#181818"
red     = "#ac4242"
green   = "#909d64"
yellow  = "#f4bf75"
blue    = "#6a9fb5"
magenta = "#aa759f"
cyan    = "#75b5aa"
white   = "#d8d8d8"

[colors.bright]
black   = "#626262"
red     = "#ff5454"
green   = "#b8cc63"
yellow  = "#e6c547"
blue    = "#6cb6eb"
magenta = "#c888c8"
cyan    = "#80b8b5"
white   = "#ffffff"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

# カーソル設定
[cursor]
# カーソルの形状: Block, Underline, Beam
style = { shape = "Block", blinking = "On" }
